server:
    port: 8082
spring:
    application:
        name: User Microservice 
    datasource:
        password: admin
        url: jdbc:postgresql://localhost:5432/user-db-test
        username: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    profiles:
        active: dev
#logging configs        
logging:
 file:
   name: C:\My Personal\Programming\test\logs\user.log
   # path:C:\My Personal\Programming\test\logs

#logging configs
#management:
 # endpoints:
  #  web:
   #   exposure:
    #    include:
     #   - '*'
     
password:
  hashing:
    algo:
      argon2:
         type: 1
         saltLength:   16
         hashLength:   32
         iterations:   4
         memory:       65586
         parralellism: 2